/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KinstControlRouteImport } from './routes/kinst-control'
import { Route as ApiPublicLibraryRouteImport } from './routes/api/public/library'
import { Route as ApiPublicFSplatRouteImport } from './routes/api/public/f.$'
import { Route as ApiPublicManifestIdRouteImport } from './routes/api/public/manifest.$id'
import { Route as ApiPublicPSplatRouteImport } from './routes/api/public/p.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KinstControlRoute = KinstControlRouteImport.update({
  id: '/kinst-control',
  path: '/kinst-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLibraryRoute = ApiPublicLibraryRouteImport.update({
  id: '/api/public/library',
  path: '/api/public/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFSplatRoute = ApiPublicFSplatRouteImport.update({
  id: '/api/public/f/$',
  path: '/api/public/f/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestIdRoute = ApiPublicManifestIdRouteImport.update({
  id: '/api/public/manifest/$id',
  path: '/api/public/manifest/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPSplatRoute = ApiPublicPSplatRouteImport.update({
  id: '/api/public/p/$',
  path: '/api/public/p/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kinst-control': typeof KinstControlRoute
  '/api/public/library': typeof ApiPublicLibraryRoute
  '/api/public/f/$': typeof ApiPublicFSplatRoute
  '/api/public/manifest/$id': typeof ApiPublicManifestIdRoute
  '/api/public/p/$': typeof ApiPublicPSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kinst-control': typeof KinstControlRoute
  '/api/public/library': typeof ApiPublicLibraryRoute
  '/api/public/f/$': typeof ApiPublicFSplatRoute
  '/api/public/manifest/$id': typeof ApiPublicManifestIdRoute
  '/api/public/p/$': typeof ApiPublicPSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kinst-control': typeof KinstControlRoute
  '/api/public/library': typeof ApiPublicLibraryRoute
  '/api/public/f/$': typeof ApiPublicFSplatRoute
  '/api/public/manifest/$id': typeof ApiPublicManifestIdRoute
  '/api/public/p/$': typeof ApiPublicPSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kinst-control'
    | '/api/public/library'
    | '/api/public/f/$'
    | '/api/public/manifest/$id'
    | '/api/public/p/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kinst-control'
    | '/api/public/library'
    | '/api/public/f/$'
    | '/api/public/manifest/$id'
    | '/api/public/p/$'
  id:
    | '__root__'
    | '/'
    | '/kinst-control'
    | '/api/public/library'
    | '/api/public/f/$'
    | '/api/public/manifest/$id'
    | '/api/public/p/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KinstControlRoute: typeof KinstControlRoute
  ApiPublicLibraryRoute: typeof ApiPublicLibraryRoute
  ApiPublicFSplatRoute: typeof ApiPublicFSplatRoute
  ApiPublicManifestIdRoute: typeof ApiPublicManifestIdRoute
  ApiPublicPSplatRoute: typeof ApiPublicPSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinst-control': {
      id: '/kinst-control'
      path: '/kinst-control'
      fullPath: '/kinst-control'
      preLoaderRoute: typeof KinstControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/library': {
      id: '/api/public/library'
      path: '/api/public/library'
      fullPath: '/api/public/library'
      preLoaderRoute: typeof ApiPublicLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/f/$': {
      id: '/api/public/f/$'
      path: '/api/public/f/$'
      fullPath: '/api/public/f/$'
      preLoaderRoute: typeof ApiPublicFSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest/$id': {
      id: '/api/public/manifest/$id'
      path: '/api/public/manifest/$id'
      fullPath: '/api/public/manifest/$id'
      preLoaderRoute: typeof ApiPublicManifestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/p/$': {
      id: '/api/public/p/$'
      path: '/api/public/p/$'
      fullPath: '/api/public/p/$'
      preLoaderRoute: typeof ApiPublicPSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KinstControlRoute: KinstControlRoute,
  ApiPublicLibraryRoute: ApiPublicLibraryRoute,
  ApiPublicFSplatRoute: ApiPublicFSplatRoute,
  ApiPublicManifestIdRoute: ApiPublicManifestIdRoute,
  ApiPublicPSplatRoute: ApiPublicPSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
